services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ai_study_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ai_study_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
